//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2.Northwind.OOC.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Order_Details
    {
        [DataMember] public int OrderID { get; set; }
        [DataMember] public int ProductID { get; set; }
        [DataMember] public decimal UnitPrice { get; set; }
        [DataMember] public short Quantity { get; set; }
        [DataMember] public float Discount { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
